export const CHANGE_INPUT_VALUE = 'change_input_value' 
export const ADD_TODO_ITEM = 'add_todo_item' 
export const DELETE_TODO_ITEM = 'delete_todo_item' 
export const INIT_LIST_ACTION = 'init_list_action'
export const INIT_TODO_ACTION = 'init_todo_action'